config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :anagramas
  root 'welcome#index'

 
end

app/models/anagrama.rb
class Anagrama < ApplicationRecord
    validates :palavra1, presence: true
    validates :palavra2, presence: true
    def verificar
        palavra1.downcase.chars.sort.join.squish==palavra2.downcase.chars.sort.join.squish
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/anagramas_controller.rb
class AnagramasController < ApplicationController

    def show
        @anagrama = Anagrama.find(params[:id])
    end
    
    def new
        @anagrama=Anagrama.new
    end
    
    def create
        @anagrama = Anagrama.new(anagrama_params)
        @anagrama.resultado = @anagrama.verificar
        
        if @anagrama.save 
            redirect_to @anagrama
            
        else
            render 'new'
        end
    end
    
    def destroy
        @anagrama = Anagrama.find(params[:id])
        @anagrama.destroy
        redirect_to @anagrama
end
        def index
        @anagramas = Anagrama.all
    end
    
    
    private
        def anagrama_params
            params.require(:anagrama).permit(:palavra1, :palavra2)
        end  
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/anagramas/index.html.erb
<h1>Resultados:</h1>
 
<table>
  <tr>
    <th>Palavra 1</th>
    <th>Palavra 2</th>
    <th>Resultado</th>
      
  </tr>
 
  <% @anagramas.each do |anagrama| %>
    <tr>
        
      <td><%= anagrama.palavra1 %></td>
      <td><%= anagrama.palavra2 %></td>
       
      <td>  <% if anagrama.resultado %>
        <%= "são anagramas!" %>
    <% else %>
        <%= "Não são anagramas!"%>   
    <%end%></td>
      <td><%= link_to 'Mostrar', anagrama_path(anagrama) %></td>
      <td><%= link_to 'Apagar', anagrama_path(anagrama),
              method: :delete%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Inicio', welcome_index_path %>
<%= link_to 'Novo Anagrama', new_anagrama_path %>

app/views/anagramas/new.html.erb
<h1>Novo Anagrama</h1>

<%= form_with scope: :anagrama, url: anagramas_path do |form| %>

    <% if @anagrama.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@anagrama.errors.count, "error") %> O anagrama não pode ser verificado:
      </h2>
      <ul>
        <% @anagrama.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <p>
    <%= form.label :primeira_palavra %><br>
    <%= form.text_field :palavra1 %>
  </p>
 
  <p>
    <%= form.label :segunda_palavra %><br>
    <%= form.text_field :palavra2 %>
  </p>
 
  <p>
    <%= form.submit "Verificar" %>
  </p>
<% end %>


<%= link_to 'Voltar', anagramas_path %>

app/views/anagramas/show.html.erb
<p>
  <strong>Palavra 1:</strong>
  <%= @anagrama.palavra1 %>
</p>
 
<p>
  <strong>Palavra 2:</strong>
  <%= @anagrama.palavra2 %>
</p>

<p>
  <strong>Resultado:</strong>
    <% if @anagrama.resultado %>
        <%= "são anagramas!" %>
    <% else %>
        <%= "Não são anagramas!"%>   
    <%end%>

</p>

<%= link_to 'Back', anagramas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Aplicativos</h1>
<%= link_to 'Verificador de Anagramas!', controller: 'anagramas' %>